CREATE TABLE public."User" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  password text NOT NULL
);

CREATE TABLE public."AgeGroups" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  age_group text NOT NULL,
  min_age smallint NOT NULL,
  max_age smallint NOT NULL
);

CREATE TABLE public."Category" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL
);

CREATE TABLE public."Questions" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  text text NOT NULL,
  answers text[] NOT NULL,
  correct_answer smallint NOT NULL,
  image_path text NULL,
  age_group_id bigint NOT NULL REFERENCES public."AgeGroups"(id) ON DELETE CASCADE,
  category_id bigint NOT NULL REFERENCES public."Category"(id) ON DELETE CASCADE
);

CREATE TABLE public."Leaderboard" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  score bigint NOT NULL,
  user_id bigint NOT NULL REFERENCES public."User"(id) ON DELETE CASCADE,
  age_group_id bigint NOT NULL REFERENCES public."AgeGroups"(id) ON DELETE CASCADE,
  category_id bigint NOT NULL REFERENCES public."Category"(id) ON DELETE CASCADE,
  correct_num bigint NOT NULL,
  false_num bigint NOT NULL,
  game_id uuid NOT NULL
);