-- Create the "parent" tables first

CREATE TABLE public."User" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL
);

CREATE TABLE public."AgeGroups" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  age_group text NOT NULL,
  min_age smallint NOT NULL,
  max_age smallint NOT NULL
);

CREATE TABLE public."Category" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL
);

-- Create the "child" tables that reference the parent tables

CREATE TABLE public."Questions" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  text text NOT NULL,
  answers text[] NOT NULL,
  correct_answer smallint NOT NULL,
  image_path text NULL,
  age_group_id bigint NOT NULL REFERENCES public."AgeGroups"(id),
  category_id bigint NOT NULL REFERENCES public."Category"(id)
);

CREATE TABLE public."Leaderboard" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  score bigint NOT NULL,
  user_id bigint NOT NULL REFERENCES public."User"(id),
  age_group_id bigint NOT NULL REFERENCES public."AgeGroups"(id)
  correct_num bigint NOT NULL
  false_num bigint NOT NULL
  game_id uuid NOT NULL
);